#!/bin/bash
#SBATCH --job-name=ADE20_slak_ssl_9x9_layer_wise
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node=4
#SBATCH --gpus=4
#SBATCH -t 3-12:00:00
#SBATCH --exclusive
#SBATCH --cpus-per-task=72
#SBATCH -o ADE20_slak_ssl_9x9_layer_wise.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate slak



 bash tools/dist_train.sh   configs/upernet_slak_tiny_512_160k_ade20k_ss_SSL_9x9.py 1   \
  --work-dir /projects/0/prjste21060/projects/Segmentation/ADE20_slak_tiny_9x9_ssl_160/  --auto-resume  --seed 0 --deterministic


source deactivate
